-- MySQL Script generated by MySQL Workbench
-- 11/01/16 15:07:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `prava`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prava` ;

CREATE TABLE IF NOT EXISTS `prava` (
  `idprava` INT NOT NULL,
  `nazev` VARCHAR(20) NOT NULL,
  `vaha` INT(2) NOT NULL,
  PRIMARY KEY (`idprava`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `uzivatele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uzivatele` ;

CREATE TABLE IF NOT EXISTS `uzivatele` (
  `iduzivatel` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(60) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `idprava` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`iduzivatel`),
  INDEX `fk_uzivatele_prava_idx` (`idprava` ASC),
  CONSTRAINT `fk_uzivatele_prava`
    FOREIGN KEY (`idprava`)
    REFERENCES `prava` (`idprava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `prava`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `prava` (`idprava`, `nazev`, `vaha`) VALUES (1, 'Administrator', 10);
INSERT INTO `prava` (`idprava`, `nazev`, `vaha`) VALUES (2, 'Recenzent', 5);
INSERT INTO `prava` (`idprava`, `nazev`, `vaha`) VALUES (3, 'Autor', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uzivatele`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `uzivatele` (`iduzivatel`, `jmeno`, `login`, `heslo`, `email`, `idprava`) VALUES (1, 'David Bárta', 'db', '$2y$10$8hEIM9FruUfU6FClNcopyO91KVs8ZFj0XXGf.vyfo/ygNpLKGfp8i', 'db@db.com', 1);
INSERT INTO `uzivatele` (`iduzivatel`, `jmeno`, `login`, `heslo`, `email`, `idprava`) VALUES (2, 'Honza', 'h', '$2y$10$0A3LX0BaVigIZujPIKke2ecqEScI1ap/4ZZfHXBZGC4JX.2Kd.73W', 'h@h.com', 3);
INSERT INTO `uzivatele` (`iduzivatel`, `jmeno`, `login`, `heslo`, `email`, `idprava`) VALUES (3, 'Pokusný uživatel', 'pokus', '$2y$10$HKJz3KPRUFfs72v31eMCcefIl.QTljJdFXzLBzeJWfIbqVhPhFZ/G', 'pokus@pokus.com', 2);
INSERT INTO `uzivatele` (`iduzivatel`, `jmeno`, `login`, `heslo`, `email`, `idprava`) VALUES (4, 'Autor číslo 1', 'autor1', '$2y$10$gW/i0ZD.itf4J.5VNotBJuebgSokIUdMwqUNWsjOFeDoGumPDLpq6', 'a1@a1.com', 3);
INSERT INTO `uzivatele` (`iduzivatel`, `jmeno`, `login`, `heslo`, `email`, `idprava`) VALUES (5, 'Autor číslo 2', 'autor2', '$2y$10$tQV.LXsLcD5UuH/C4bRMH.7SomSKxqVKX66dnk9kugahEmC.aAx5O', 'a2@a2.com', 3);
INSERT INTO `uzivatele` (`iduzivatel`, `jmeno`, `login`, `heslo`, `email`, `idprava`) VALUES (6, 'Recenzent 1', 'rec1', '$2y$10$MP7ypwvaF29/GoS68zEpkO5kZ7s01vejdUcqLXzLuKwiflFYo.rvG', 'r1@r1.com', 2);
INSERT INTO `uzivatele` (`iduzivatel`, `jmeno`, `login`, `heslo`, `email`, `idprava`) VALUES (7, 'Recenzent 2', 'rec2', '$2y$10$ca.4Ht8qnl/qSCbpp2cwzeaXPUnLQHfCfTmpkfEh7D3mJEn4fasMG', 'r2@r2.com', 2);

COMMIT;

